### ISSUE TITLE
Headless build crashes

### ISSUE THREAD

**Issue by rotolonico** [vis2k/DOTSNET#15]
**Describe the bug**
After building the Physics example scene in headless mode, the App crashes on startup.

**To Reproduce**
1. Go to the Physics scene
2. Build the scene with the "Server build" Unity setting ticked on
3. Run the App

**Desktop (please complete the following information):**
 - OS: Linux, Fedora 32

**Additional Info**
I have attached the Player.log file
[Player.log](https://github.com/vis2k/DOTSNET/files/5012025/Player.log)

**Comment by vis2k** [comment]
hey, just checked your log. there is a Nullreferencexception:

NullReferenceException: Object reference not set to an instance of an object
  at DOTSNET.NetworkServerSystem.StartServer () [0x00022] in <ea22c05482ce4d0bb08bd55558084c17>:0 
  at DOTSNET.NetworkServerAuthoring.Awake () [0x00039] in <c61b3e9b25c24a77ac8bb8a8c2e0542f>:0 

Can you check if there is anything null that shouldn't be?

**Comment by rotolonico** [comment]
After doing some debugging I found out the game would not crash if I deactivated all spawnable gameobjects (the 4 walls in the Physics scene). So the problem might be in the Gameobject to Entity conversion? Anyway, since it's a server build, those gameobjects weren't needed anyway so that solved my problem.

**Comment by vis2k** [comment]
hm ok. I’ll still try a server build later

**Comment by vis2k** [comment]
ok tried it myself.
I used Unity 2020.1.16 and google cloud debian, ran it in xterm.
works fine with physics demo.

if anyone else has this problem then feel free to reopen.
