### ISSUE TITLE
Errors during runtime

### ISSUE THREAD

**Issue by danyaegoist** [vis2k/DOTSNET#16]
**Describe the bug**
I just install 
- Unity 2019.f.6f1
- Burst 1.3.0
- Entities 0.11.0
- Physics 0.3.2
- DOTSNET 1.14

And i have errors after building examples on 

**To Reproduce**
1. Install latest unity, and import DOTSNET
2. Add example scene from DOTSNET to build
3. Build
4. Try to run server(or client, if you run server in editor) in build-ed app
5. You will see errors in console debugger.
 
**Expected behavior**
Must run like in unity editor, smooth and without errors.

**Screenshots**
[screenshot](https://i.imgur.com/uKLoeWM.png)

**Desktop (please complete the following information):**
 - Windows 10 x64

**Additional context**
In editor all works fine.

**Comment by vis2k** [comment]
@danyaegoist what system do you use?
the DLL is from Apathy, which only works on 64 bit computers. Which is pretty much the standard now :)

**Comment by vis2k** [comment]
If you need 32 bit then you can also remove apathy and use the LiteNetLib transport instead.

**Comment by danyaegoist** [comment]
My [system](https://i.imgur.com/Of0uBJG.png). I need x64

**Comment by vis2k** [comment]
@danyaegoist can you select network.bindings dll in unity editor and check which platform it has selected for you?
sounds like it's x86 instead of x64

**Comment by danyaegoist** [comment]
@vis2k [here](https://i.imgur.com/8YMViwG.png)

**Comment by danyaegoist** [comment]
@vis2k Problem, that i just include dotsnet and dont touch anything, just add example scene to build and build.
