### ISSUE TITLE
Dependency Injection documentation has code example errors

### ISSUE THREAD

**Issue by Kerozard** [vis2k/DOTSNET#21]
**Describe the bug**
GetExistingSystem<T>() is used incorrectly in multiple places in the Dependency Injection section of the documentation.

Direct Link:
https://docs.google.com/document/d/14l5hz3QJ1Aw8nuVTrbrAtr-UoGBiXyvToW_tO5jYcQg/edit#heading=h.ii1agvl4wmw

**To Reproduce**
1. Go to the Dependency Injection section of the documentation

**Expected behavior**
The presented syntax should be correct.

For Example:
`server = GetExistingSystem<NetworkServerSystem>().;`

Apart from the trailing dot, it should probably be 

`server = World.GetExistingSystem<NetworkServerSystem>();`

since the Bootstrap references are not set yet when autocreated systems are being set up.

**Comment by vis2k** [comment]
Hey, thanks for feedback.
The example was mostly to show what we **dont** need to do anymore, so I used the shorter syntax :)
