### ISSUE TITLE
Expose Transport Configurations

### ISSUE THREAD

**Issue by Piefayth** [vis2k/DOTSNET#22]
**Is your feature request related to a problem? Please describe.**
Can't configure my transport (in my case, LiteNetLib) to use all the available features. I assume the other transports are similarly underexposed, but I honestly haven't looked.

**Describe the solution you'd like**
I think what would be nice is a way to let the user customize the whole client creation, maybe by offering some sort of hook where we can return a custom NetManager.

I know you've talked about doing this a bit on Discord, I just wanna confirm the scope of access to NetManager will allow me to do all the fun LNL things. I realize I can just make my own transport if I want to muck around with, say, the listener settings, but I'd rather not, haha.

**Comment by vis2k** [comment]
@Piefayth sure, can expose more settings. which ones do you need?

**Comment by Piefayth** [comment]
The ones that made me ask are

`SimulatePacketLoss`
`SimulateLatency`
`SimulationPacketLossChance`
`SimulationMinLatency`
`SimulationMaxLatency`

**Comment by vis2k** [comment]
thanks for report. settings are exposed in V1.18:
![2020-08-28_17-11-02](https://user-images.githubusercontent.com/16416509/91583433-8159f300-e951-11ea-9f92-bb2f0ebc5705.png)
