### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jtrpc** [vis2k/DOTSNET#24]
After importing, the following error appears and the example scene cannot be played.

<img width="540" alt="001" src="https://user-images.githubusercontent.com/45491907/90962658-95829800-e4ec-11ea-9ece-e97df95990d4.png">

**Comment by vis2k** [comment]
@jtrpc which Unity version do you use?
make sure to use exactly Unity 2020.1.2f1 with exactly the following packages:
![2020-08-23_23-03-43](https://user-images.githubusercontent.com/16416509/90988670-e77ef880-e594-11ea-987d-c01de1b6e30a.png)
