### ISSUE TITLE
DestroyAllNetworkEntities() does not considers entities with LinkedEntityGroup in NetworkClientSystem

### ISSUE THREAD

**Issue by shinyclef** [vis2k/DOTSNET#28]
This is basically a reopening of issue: https://github.com/vis2k/DOTSNET/issues/11
Basically, the fix was applied to NetworkServerSystem, but NetworkClientSystem is still experiencing the issue.
Fix is to just apply the new code to NetworkClientSystem as well, it's just a few lines to copy paste.

**Comment by miwarnec** [comment]
fix is in next version. thanks!
