### ISSUE TITLE
Sync entity name across worlds

### ISSUE THREAD

**Issue by vipvex** [vis2k/DOTSNET#4]
`EntityManager.SetName(entity, "my_custom_entity_name");`

It would be nice to sync the entity names across the worlds/servers. This would make debugging much better easier.

Right now the Translation & Rotation components in newly spawned entities are synced automatically. It would be great to have the name synced as well.

**Comment by vis2k** [comment]
Hey @vipvex , sadly Unity decided to make SetName/GetName an editor-only debugging feature.
It's not available in builds :(

Feel free to reopen if this doesn't make sense
