### ISSUE TITLE
Entities invisible with URP and Hybrid Renderer V2

### ISSUE THREAD

**Issue by vP3nguin** [vis2k/DOTSNET#41]
**Describe the bug**
Entities are invisible with URP and Hybrid Renderer V2 if they are created in sceneview and attached "Convert To Entity" with "Convert and Destroy" to them. Spawned prefabs at runtime are instead visible and working just fine.

**To Reproduce**
1. Create a new Project
2. Import DOTSNET and Universal RP
3. Enable Hybrid Renderer V2 and convert materials to URP 
4. Open Benchmark Scene and click Play
-> Ground is **not** visible in scene but the entity was created and shows up in the Entity Debugger
-> When starting server and connecting client, all spawned monsters and the player are instead visible

**DOTSNET Version**
 - 1.26

**Comment by vP3nguin** [comment]
**Small Update/Workaround:**
With "Convert To **Network** Entity" and "Convert and Destroy" it works just fine, because it's not in the DefaultWorld.

Is this the expected behaviour or should the DefaultWorld also be rendered? @vis2k

**Comment by miwarnec** [comment]
I vaguely remember reading that hybrid renderer v2  (or URP?) can only render in one world.
so that's expected.
feel free to ask unity about supporting two worlds, which is probably not gonna happen

**Comment by miwarnec** [comment]
added a chapter to docs https://dotsnet.gitbook.io/docs/user-manual/hybrid-renderer-v2-urp
