### ISSUE TITLE
Shift DOTSNET to a package to utilize the Unity Package Manager

### ISSUE THREAD

**Issue by toomasio** [vis2k/DOTSNET#42]
Similar to how A* implements it https://arongranberg.com/astar/download you put in your invoice order number and it allows you to use the package manager instead of the asset store. Might also help bypass the Unity Store's verification process every time you release an update.

**Comment by miwarnec** [comment]
asset store assets should show in your package manager in recent unity versions.
if I am misunderstanding, feel free to reopen
