### ISSUE TITLE
No way to join a server world without creating a prefab.

### ISSUE THREAD

**Issue by vipvex** [vis2k/DOTSNET#5]
I'd like a player to join the server but not spawn any prefabs. However the only method that exists must accept a prefab.

```
server.JoinWorld(connectionId, player); // The only current way to join a world.
server.JoinWorld(connectionId) // Not allowed currently
```
  
Such as in this example:
![join network](https://user-images.githubusercontent.com/6335405/86611783-08977580-bf64-11ea-8273-1bb0b8c22dc6.PNG)

**Comment by vis2k** [comment]
Hey @vipvex ,
'joined world' means that the player is literally in the 3D world now. so by that definition, it makes sense that you need to spawn a prefab.

before joining, players are in server.connections dictionary.

in your case, you can also join with an empty prefab. 

closing for now. if it doesn't make sense, please reopen and explain the use case :)
