### ISSUE TITLE
Quaternion Compression/Decompression bug

### ISSUE THREAD

**Issue by Nyert** [vis2k/DOTSNET#57]
[**Describe the bug**
when rotating the character over the network, it sometimes flips

**[IMPORTANT] How can we reproduce the issue, step by step:**
to reproduce it i used the physics scene and made some slight changes, server driven physics +  changed the movement to have an horizontal only rotation
1. Install the package in a DOTSNET 1.38 project and apply the [DOTSNET Modified Physics Example](https://cdn.discordapp.com/attachments/705707645776035870/916051369083944980/DOTSNET_physicsExample.unitypackage)to it 
2. Play the scene 
2. Use your mouse to rotate around in the same direction, with different speeds 
3. Repeat 2 until the Capsule (character) flips out on itself even though he is not supposed to, this never happen without the quaternion compression
it is quite an inconsistent bug so reproducing it can happen right away or take some time.

**Expected behavior**
the capsule(character) shouldn't flip around

**Desktop (please complete the following information):**
 - OS: Windows
 - Unity 2020.3.22f1
 - DOTSNET 1.38

Contact me on DOTSNET discord for additional info on DrBoum

https://user-images.githubusercontent.com/55545442/144494715-e100013b-5a99-4fce-a904-3fb35c8a92ba.mp4

**Comment by miwarnec** [comment]
fix is in next version :)
