### ISSUE TITLE
FixedString* serialization changes from IBit* to Network*

### ISSUE THREAD

**Issue by Will-Carson** [vis2k/DOTSNET#63]
This is less of a feature request and more of a question. IBitReader/Writer would only write the content of FixedString* types to messages, where NetworkReader/Writer writes the whole FixedString, empty bytes and all. What is the reason for this regression? Did we get a huge performance increase? If you say it's worth it I'll believe you, but my understanding is that CPU time is generally a lot less expensive then network traffic, so the IBitReader/Writer tradeoff seems better to me. In the meantime I will be writing an extension to NetworkReader/Writer to mimic the behavior of IBit*, but I am curious as to the explanation for this change.

**Comment by miwarnec** [comment]
Hi, yes thats true for two reasons:
- blittable writing the whole thing is faster 
- delta compression needs the full size of the string anyway. cant have dynamically sized data types

in other words, its faster and still bandwidth efficient thanks to the delta compression filtering out the bytes that are same as last time :)
